# Generated by Django 4.2.7 on 2025-08-07 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "starfavs",
            "0003_delete_movie_delete_planet_remove_user_date_joined_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Favorite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("custom_title", models.CharField(max_length=200)),
                ("original_name", models.CharField(max_length=200)),
                ("external_record_id", models.CharField(max_length=50)),
                (
                    "record_type",
                    models.CharField(
                        choices=[("movie", "Movie"), ("planet", "Planet")],
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorites",
                        to="starfavs.user",
                    ),
                ),
            ],
            options={
                "db_table": "starfavs_favorites",
                "unique_together": {("user", "external_record_id", "record_type")},
            },
        ),
    ]
