# Generated by Django 4.2.7 on 2025-08-07 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("starfavs", "0004_favorite"),
    ]

    operations = [
        migrations.AlterField(
            model_name="favorite",
            name="custom_title",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
